# Site settings
locale: "ko"
title:          Hyoyoung Kim
description:    " :) "
url:            "https://hyngkm.github.io"

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X

# Site Author
author:
  name:         Hyoyoung Kim
  url:          https://hyngkm.github.io
  email:        hyoyoung.j.kim@gmail.com
  big:          Product Designer
  location:     Seoul, S.Korea
  
# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
